### ISSUE TITLE
gestures.h missing

### ISSUE THREAD

**Issue by Justinzobel** [hugegreenbug/xf86-input-cmt#10]
Using 2.0.1 tarball

./gesture.h:11:31: fatal error: gestures/gestures.h: No such file or directory
 #include <gestures/gestures.h>

**Comment by hugegreenbug** [comment]
You need to install libgestures and libevdevc before compiling this driver.
https://github.com/hugegreenbug/libgestures  and
https://github.com/hugegreenbug/libevdevc .

Hugh

**Comment by Justinzobel** [comment]
Thanks!
