### ISSUE TITLE
Trackpad driver affects the behaviour of a USB mouse

### ISSUE THREAD

**Issue by ColtonDRG** [hugegreenbug/xf86-input-cmt#14]
Whenever the driver is installed, my USB mouse behaves incorrectly, more specifically scrolling acceleration, and pointer speed/acceleration.

**Comment by ColtonDRG** [comment]
I have been informed (by you) that this is due to a configuration file for the mouse, and can be disabled quite easily. Feel free to close.

**Comment by Madouc** [comment]
can you please elaborate on which configuration file there was and how you disabled it,
because i have a similar issue with the vertical scrolling on my Logitech USB mouse.
