### ISSUE TITLE
configuration file "50-touchpad-cmt-peppy.conf" gets overwritten 

### ISSUE THREAD

**Issue by ajinkyakolhe112** [hugegreenbug/xf86-input-cmt#23]
Hi,
I wanted to set following properties to touchpad
        Option "TapButton2" "2"
        Option "TapButton3" "3"
        Option "MaxTapMove" "20"
        Option "MaxTapTime" "140"
        Option "ClickTime" "5"
        Option "FingerHigh" "15"
        Option "FingerLow" "12"
        Option "LockedDrags" "true"
        Option "LockedDragTimeout" "300"

But any changes I do are getting overwritten.

**Comment by trey-k** [comment]
I'm running GaOS and I've got my Toshiba Chromebook 2 erasing changes from my xf86-input-cmt conf on reboot as well, according to the git release /usr/share/X11/xorg.conf.d/50-touchpad-cmt-swanky.conf SHOULD be where I would save my config

**Comment by ajinkyakolhe112** [comment]
Create a new directory: sudo mkdir /etc/X11/xorg.conf.d/
and create Create a new directory: sudo mkdir /etc/X11/xorg.conf.d/50-touchpad-cmt-swanky.conf 

And paste the contents:

Section "InputClass"
    Identifier      "touchpad peppy cyapa"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    MatchProduct    "cyapa"
    Option "Whatever" "Value"
    Option "Whatever2" "Value2"
EndSection

Edit "Whatever" to what you want, of course. You don't have to repeat anything that is already in /usr/share/X11/xorg.conf.d/50-touchpad-cmt-peppy.conf, just put your own options in /etc/X11/xorg.conf.d/51-touchpad-cmt-peppy.conf. Updates won't overwrite these.
