### ISSUE TITLE
50-touchpad-cmt-lulu.conf doesn't have smooth/coasting scrolling

### ISSUE THREAD

**Issue by ghost** [hugegreenbug/xf86-input-cmt#24]
Chromebook: Dell 13 i3 4GB non-touch
Crouton: Ubuntu14.04 + xfce

The scrolling stops as soon as my finger leaves touchpad, is there anyway to make it scroll like chromeos? I tried to change the values in xinput but didn't  understand  a lot of the values, is there anyway I could find a document explaining what those properties/values do?
## Thanks!

Also, sudo apt-get install xf86-input-cmt somehow didn't download lulu.conf to /usr/share/xf86-input-cmt, I had to manually copy/pasta it in a text editor. (tried both hugegreenbug/cmt and hugegreenbug/cmt2 ppa)

**Comment by hugegreenbug** [comment]
This is not a config setting. It required changes to libgestures, which I've added recently.

**Comment by ghost** [comment]
lulu.conf is not in the default xf86-input-cmt folder
