### ISSUE TITLE
C720 Trackpad configure right manual click

### ISSUE THREAD

**Issue by Timvrakas** [hugegreenbug/xf86-input-cmt#4]
Hello! I just installed this driver onto my crouton 14.04 unity installation, and I'm wondering how to configure the manual right click, (as opposed to 2-finger tap to click). I can do a 2-finger+click, but I would like to be able to just click in the lower right corner if that is possible.

I looked through the xinput props, but there are so many, and I didn't see any that sounded like they were related to this.

Thanks!

**Comment by hugegreenbug** [comment]
This has been added to the most recent version. Also, I added an option to set the size of the right click area.
