### ISSUE TITLE
Need help with `make install` after building

### ISSUE THREAD

**Issue by darcyparker** [hugegreenbug/xf86-input-cmt#6]
I am trying to build & install the touchpad driver for a Debian (jessie) chroot.
.
I built and installed the dependencies libgestures and libevdevc successfully.

The instructions here: https://github.com/hugegreenbug/xf86-input-cmt#compiling suggest there's a `./configure` script which is not in the repo. but I created it with `autoreconf -v --install` like this:

```bash
./apply_patches.sh
autoreconf -v --install
./configure --prefix=/usr
make
sudo make install
```
I can see `xf86-input-cmt/src/.libs/cmt_drv.so` and other files are created by the `make` step.  And I see that `sudo make install` copies the files to `/usr/lib/xorg/modules/input`

I then setup the configuration files like this

```bash
  sudo mv /usr/share/X11/xorg.conf.d/50-synaptics.conf /usr/share/X11/xorg.conf.d/50-synaptics.conf.old
  sudo cp ~/src/xf86-input-cmt/xorg-conf/20-mouse.conf /usr/share/X11/xorg.conf.d
  sudo cp ~/src/xf86-input-cmt/xorg-conf/40-touchpad-cmt.conf /usr/share/X11/xorg.conf.d
  sudo cp ~/src/xf86-input-cmt/xorg-conf/50-touchpad-cmt-peppy.conf /usr/share/X11/xorg.conf.d
```

After shutting down and restarting my chroot I don't see the new cmt touchpad in the list under XFCE's Mouse and Touchpad settings tool.  I just see `Cypress APA Trackpad (cypa)`.  

I also don't see it with `xinput`.  This is what I see:

```
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ Cypress APA Trackpad (cyapa)              id=11   [slave  pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
    ↳ Power Button                              id=6    [slave  keyboard (3)]
    ↳ Video Bus                                 id=7    [slave  keyboard (3)]
    ↳ Power Button                              id=8    [slave  keyboard (3)]
    ↳ Sleep Button                              id=9    [slave  keyboard (3)]
    ↳ Sleep Button                              id=10   [slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard              id=12   [slave  keyboard (3)]
```

I feel like I am so close to getting it installed... but stuck.  Do you have any suggestions? - Thanks

**Comment by hugegreenbug** [comment]
I created the config file by running the autogen.sh script:

sh autogen.sh

Make sure you have: xutils-dev and libtool installed for the macros.


Hugh

**Comment by darcyparker** [comment]
I created the configuration file that way too and I have the dependencies `libjsoncpp-dev xutils-dev xserver-xorg-dev xinput`...  and it appears things built correctly. (I can see `xf86-input-cmt/src/.libs/cmt_drv.so` and other files are created by the `make` step.  And I see that `sudo make install` copies the files to `/usr/lib/xorg/modules/input`.)

My problem is that after running `sudo make install` and copying the configuration files mentioned above, I don't see the new touchpad cmt driver.  I am missing something, but not sure what to do to see the new driver with `xinput`.

**Comment by hugegreenbug** [comment]
Ok, I misunderstood. Maybe the synaptic driver is loaded instead? You can
check in /var/log/Xorg.0.log. You can disable the synaptic driver by moving
the synaptics config file out of the way or by commenting out each line in
the file. I'm on Ubuntu and the synaptics driver config file is:
/usr/share/X11/xorg.conf.d/50-synaptics.conf .

Hugh

**Comment by darcyparker** [comment]
NP - Thanks for your help @hugegreenbug.  I figured it out after some trial and error and carefully re-reading the instructions.  The driver is installed and working very nicely now.  If others have an issue, they can refer to my gist here: https://gist.github.com/darcyparker/3d89e7851fc10992000e
