### ISSUE TITLE
ABI Version mismatch 20 vs servers 21

### ISSUE THREAD

**Issue by ponkon** [hugegreenbug/xf86-input-cmt#7]
I can't get the cmt driver to load and I think it's because of an ABI version mismatch. Here's the errors I'm getting in /var/log/Xorg.0.log

[   374.327] (**) Cypress APA Trackpad (cyapa): Applying InputClass "touchpad wolf cyapa"
[   374.328] (II) LoadModule: "cmt"
[   374.328] (II) Loading /usr/lib/xorg/modules/input/cmt_drv.so
[   374.329] (II) Module cmt: vendor="X.Org Foundation"
[   374.329] 	compiled for 1.15.1, module version = 0.0.1
[   374.329] 	Module class: X.Org XInput Driver
[   374.329] 	ABI class: X.Org XInput driver, version 20.0
[   374.329] (EE) module ABI major version (20) doesn't match the server's version (21)
[   374.329] (II) UnloadModule: "cmt"
[   374.329] (II) Unloading cmt
[   374.330] (EE) Failed to load module "cmt" (module requirement mismatch, 0)
[   374.330] (EE) No input driver matching `cmt'
[   374.330] (II) config/udev: Adding input device Cypress APA Trackpad (cyapa) (/dev/input/mouse1)
[   374.330] (II) No input driver specified, ignoring this device.
[   374.330] (II) This device may have been added with another device file.

Dell chromebook 11 ubuntu 14.04 LTS
kernel 3.16.0-37-generic

I installed via the ppa.
Is there a way I could either change the ABI version of the cmt driver or the version of the xorg server?

Thanks in advance!

**Comment by hugegreenbug** [comment]
The driver in the ppa was compiled with the X server provided by:
xserver-xorg-core. I think you have installed the utopic version
(xserver-xorg-core-lts-utopic I think). I guess they are shipping with that
version now. If you install: xserver-xorg-core, it will the correct
packages and you can use this driver.

Hugh

**Comment by hugegreenbug** [comment]
Hopefully, that won't uninstall packages you need. Make sure the
ubuntu-desktop package is installed after you install xserver-xorg-core.

Hugh

**Comment by hugegreenbug** [comment]
You could also try the utopic ppa. Change the source in
/etc/apt/sources.list.d/hugegreenbug...

**Comment by ponkon** [comment]
Thanks so much for the tips. I ended up installing xserver-xorg-core. It didn't work the first time and I got an error about broken packages:

E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

I removed some of the libcheese libraries then the xserver-xorg-core install worked. This driver is so much better than the synaptics one.

**Comment by ezawadzki** [comment]
This command saved my life :
````
sudo apt-get install  libglew-dev libcheese7 libcheese-gtk23 libclutter-gst-2.0-0 libcogl15 libclutter-gtk-1.0-0 libclutter-1.0-0  xserver-xorg-input-all
```
Please see [Harris answer](http://askubuntu.com/a/592440/415272)
